#!/usr/bin/env python3

import common_bf
import argparse
import requests
import time


def main():
    parser = argparse.ArgumentParser(description='Downloads BFB images and sends it to the BF.')
    parser.add_argument('-i', '--id', dest='id', default=0, action='store', type=int, help='Specify the id of the BF.')
    args = parser.parse_args()
    _ = common_bf.find_bf_pci_addresses_or_quit(args.id)

    bfb_image = "DOCA_1.5.1_BSP_3.9.3_Ubuntu_20.04-4.2211-LTS.signed.bfb"
    bfb_url = f"https://content.mellanox.com/BlueField/BFBs/Ubuntu20.04/{bfb_image}"
    r = requests.get(bfb_url)
    fn = f"/dev/rshim{args.id//2}/boot"
    print("Loading BFB image onto the BF. This will take a while")
    start = time.time()
    with open(fn, "wb") as f:
        f.write(r.content)
    print(f"It took {time.time() - start}s to load the BFB image")


if __name__ == "__main__":
    main()
