#!/usr/bin/env python3

import os
import common_bf
import argparse


def main():
    parser = argparse.ArgumentParser(
        description="Select BF to connect to with a console."
    )
    parser.add_argument(
        "-i",
        "--id",
        dest="id",
        default=0,
        action="store",
        type=int,
        help="Specify the id of the BF.",
    )
    args = parser.parse_args()
    _ = common_bf.find_bf_pci_addresses_or_quit(args.id)
    os.system(
        f"minicom --color on --baudrate 115200 --device /dev/rshim{args.id//2}/console"
    )


if __name__ == "__main__":
    main()
