#!/usr/bin/env python

import common_bf
import argparse

def main():
    parser = argparse.ArgumentParser(description='Shows firmware version.')
    parser.add_argument('-i', '--id', dest='id', default=0, action='store', type=int, help='Specify the id of the BF-2.')
    args = parser.parse_args()
    bf = common_bf.find_bf2_pci_addresses_or_quit(args.id)
    print(common_bf.mst_flint(bf)["FW Version"])

if __name__ == "__main__":
    main()