#!/usr/bin/env python3
import common_bf

def main():
    bf2s = common_bf.find_bf2_pci_addresses()
    print("ID     PCI-Address")
    print("-----  ------------")
    for (i, e) in enumerate(bf2s):
        print(f"{i: 5d}  {e}")

if __name__ == "__main__":
    main()