#!/usr/bin/env python3
import common_bf
import os
import argparse

def main():
  parser = argparse.ArgumentParser(description='Puts the BF-2 into nic mode.')
  parser.add_argument('-i', '--id', dest='id', default=0, action='store', type=int, help='Specify the id of the BF-2.')
  args = parser.parse_args()

  bf = common_bf.find_bf2_pci_addresses_or_quit(args.id)

  os.system(f"mstconfig -y -d {bf} s INTERNAL_CPU_MODEL=1")
  os.system(f"mstconfig -y -d {bf} s INTERNAL_CPU_PAGE_SUPPLIER=1")
  os.system(f"mstconfig -y -d {bf} s INTERNAL_CPU_ESWITCH_MANAGER=1")
  os.system(f"mstconfig -y -d {bf} s INTERNAL_CPU_IB_VPORT0=1")
  os.system(f"mstconfig -y -d {bf} s INTERNAL_CPU_OFFLOAD_ENGINE=1")

if __name__ == "__main__":
  main()
